import { Providers } from '@/providers/Providers';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='ru'>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
